### ISSUE TITLE
"project progress" stuck at 0% if subtitles are added

### ISSUE THREAD

**Issue by ghost** [rastersoft/devedeng#33]
When I try to create a VideoDVD with 4.5.0 and add subtitles to it then the progress bar stucks at the "creating disc" window.
Without subs everything works fine.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/devedeng/project.py", line 528, in on_create_disc_clicked
    p = movie.do_conversion(os.path.join(movie_folder,"movie_"+str(counter)+".mpg"))
  File "/usr/lib/python3.5/site-packages/devedeng/file_movie.py", line 681, in do_conversion
    self.subt_fill_color, self.subt_outline_color, self.subt_thickness)
  File "/usr/lib/python3.5/site-packages/devedeng/subtitles_mux.py", line 62, in multiplex_subtitles
    out_xml.write('" fill-color="#%02X%02X%02X"' % tuple([fill_color[i] * 255 for i in range(len(fill_color))]))
TypeError: %X format: an integer is required, not float
```

**Comment by jcowgill** [comment]
This was fixed in 4.7.0
