### ISSUE TITLE
ZeroDivisionError when adding short files to video DVD

### ISSUE THREAD

**Issue by jcowgill** [rastersoft/devedeng#43]
When adding a short (< 1 second) file to a video DVD, nothing happens and the following error is printed out:

```
Traceback (most recent call last):
  File "/usr/lib/devede/devedeng/project.py", line 230, in on_add_file_clicked
    self.add_several_files(ask_files.files)
  File "/usr/lib/devede/devedeng/project.py", line 252, in add_several_files
    new_file = devedeng.file_movie.file_movie(efile)
  File "/usr/lib/devede/devedeng/file_movie.py", line 169, in __init__
    self.original_videorate = ((8 * self.original_file_size) / self.original_length) - (self.original_audiorate * self.audio_streams)
ZeroDivisionError: division by zero
```

**Comment by rastersoft** [comment]
Fixed in repository some minutes ago. Now I'll check the one with the subtitles.
