### ISSUE TITLE
ZeroDivisionError adding short file to video DVD

### ISSUE THREAD

**Issue by BlueH2O** [rastersoft/devedeng#71]
I'm trying to add a video just over 1 minute long, but the original file is ATSC program stream in 1080 / 5.1.  I'm getting this error trying to apply properties:

`ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devedeng/file_movie.py", line 622, in on_button_accept_clicked
    self.set_final_size_aspect()
  File "/usr/local/lib/python3.6/site-packages/devedeng/file_movie.py", line 368, in set_final_size_aspect
    self.original_width, self.original_height, self.original_aspect_ratio)
  File "/usr/local/lib/python3.6/site-packages/devedeng/file_movie.py", line 252, in get_max_resolution
    tmpy = rx / aspect
ZeroDivisionError: float division by zero
`

**Comment by rastersoft** [comment]
I uploaded a patch for this. Please, test it.

**Comment by BlueH2O** [comment]
Same error, different place?

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devedeng/project.py", line 257, in on_add_file_clicked
    self.add_several_files(ask_files.files)
  File "/usr/local/lib/python3.6/site-packages/devedeng/project.py", line 289, in add_several_files
    self.refresh_disc_usage()
  File "/usr/local/lib/python3.6/site-packages/devedeng/project.py", line 413, in refresh_disc_usage
    estimated_size = f.get_estimated_size()
  File "/usr/local/lib/python3.6/site-packages/devedeng/file_movie.py", line 219, in get_estimated_size
    self.set_final_size_aspect()
  File "/usr/local/lib/python3.6/site-packages/devedeng/file_movie.py", line 415, in set_final_size_aspect
    self.original_width * self.aspect_ratio_final / midle_aspect_ratio)
ZeroDivisionError: float division by zero

**Comment by rastersoft** [comment]
Hello:

Sorry for the big delay, I've been quite busy with my job and other projects.

I just uploaded another change that should fix this one. Can you test it, please?

**Comment by BlueH2O** [comment]
Looks good to me!

**Comment by rastersoft** [comment]
Great. During today I'll prepare the new package. Thanks for the bug report!!!!
